export const PLAN_COPY = {
  firstPass: 'FIRST PASS',
  unlockLead: "Here's a first pass. 3 clubs this week. It gets less random as you get more specific.",
  unlockCta: "See this week's plan",
  homeKicker: 'This week',
  homeLead: 'A short plan. Show up to a room — not a chat.',
  homePeopleClosed: 'People are not on this pass. Clubs first.',
  first15: 'First 15 minutes',
  stayLeave: 'Stay / leave',
  thisWeek: 'This week',
  nextMeeting: 'Next meeting',
  notFit: 'Not a fit if',
  ifThen: 'If-then',
  dropIn: 'Low commitment — drop in is fine.',
  illGo: "I'll go",
  illGoDone: "You're going. We'll remind you with this same line.",
  alsoAt: 'Also at this meeting',
  alsoAtNote: 'Only people who are actually in this room. No grid. No messages.',
  reminderTitle: 'Today',
  reminderEmpty: "You haven't said I'll go yet. The reminder is the same if-then you commit — we won't invent a new one.",
  reminderNote: "This is the same if-then you committed. We won't invent a new one.",
  reminderNotifyWeb: 'On a phone in Expo Go, this same line can fire as a local notification. On web, this screen is the reminder.',
  reminderNotifyArmed: 'A local notification is armed with this same line.',
  reminderNotifyDenied: "Notifications were not allowed. This screen still holds the same if-then.",
  reminderPreview: 'Preview notification (same line, a few seconds)',
  reminderWent: 'I went',
  reminderNotToday: 'Not today',
  officerLink: 'Club officers: list a room',
  campusLink: 'Campus settings',
  officerTitle: 'List a room',
  officerLead:
    'Officers write what a newcomer does in the first 15 minutes. A club without that script is not listed. Do not invent a host.',
  officerName: 'Club / room name',
  officerFirst15: 'First 15 minutes — what a newcomer actually does',
  officerStay: 'Stay / leave',
  officerHours: 'Hours',
  officerNext: 'Next meeting (optional — hours are used if blank)',
  officerNotFit: 'Not a fit if',
  officerWalk: 'Walk instruction for the if-then (place + time, no names)',
  officerNights: 'Nights this actually meets',
  officerDropIn: 'Drop-in / low commitment is fine',
  officerSubmit: 'List this room',
  officerListed: 'Listed. It can show on the weekly plan (1–3 rooms). Missing first 15 minutes would have kept it off.',
  campusTitle: 'Campus settings',
  campusLead:
    'People stay off home until this campus has ~40–60 interviews. That is a campus flag, not a dating preference. When it opens, a club card may name who is also at that meeting. No people grid. No DM.',
  campusClosed: 'People gate closed — 0 interviews on this campus.',
  campusOpen: 'People gate open — simulating 50 interviews. Names only on the club they attend.',
  campusOpenCta: 'Simulate 50 interviews (open people on clubs)',
  campusCloseCta: 'Back to 0 interviews (clubs only)',
  homePeopleOpen: 'People are only named on a club they actually attend. No grid. No messages.',
  afterLead: 'Two taps. Show-up is the point. Coming back within 14 days is the companion.',
  stayQ: 'Did you stay past 15 minutes?',
  returnQ: 'Would you go back next week?',
  sceneQ: "What was true in the room that wasn't in the profile?",
  sceneHelper: 'A real detail from the room. Not whether you made a friend.',
  afterSave: 'Save this visit',
  reportTitle: 'Report',
  reportLead: 'Tell us what was wrong. This stays off the public card.',
  reportPlaceholder: 'What happened?',
  reportSubmit: 'Submit report',
  reportDone: 'Report saved on this device.',
  blockTitle: 'Block',
  blockLead: 'This club will leave your weekly plan. You can start another first pass later.',
  blockLeadPerson: 'This person will not show as also at a meeting. Clubs stay. No messages either way.',
  blockConfirm: 'Block this club',
  blockConfirmPerson: 'Block this person',
  blockDone: 'Blocked. It will not show on home.',
  blockDonePerson: 'Blocked. They will not show on a club card.',
  cardTitle: 'Your public card',
  cardPrivacy: 'The interview stays private. Other students only see this short card.',
  cardHint: '1–2 sentences in your words. We will not rewrite them.',
  cardSave: 'Save card',
  safetyLink: 'Report',
  blockLink: 'Block',
  editCard: 'Edit public card',
  reminderLink: 'Day-of reminder',
  afterLink: 'After a visit',
  yes: 'Yes',
  no: 'No',
} as const;
