export const PLAN_COPY = {
  firstPass: 'FIRST PASS',
  unlockLead: '3 clubs this week.',
  unlockCta: 'This week',
  homeKicker: 'This week',
  homeLead: 'Show up to a room.',
  homePeopleClosed: 'Clubs first.',
  first15: 'First 15 minutes',
  stayLeave: 'Stay / leave',
  thisWeek: 'This week',
  nextMeeting: 'Next meeting',
  notFit: 'Not a fit if',
  ifThen: 'If-then',
  dropIn: 'Drop-in',
  illGo: "I'll go",
  illGoDone: "You're going.",
  alsoAt: 'Also here',
  alsoAtNote: 'No messages.',
  reminderTitle: 'Today',
  reminderEmpty: "Say I'll go on a club first.",
  reminderNote: 'Same line you committed.',
  reminderNotifyWeb: 'On a phone, this line can notify you.',
  reminderNotifyArmed: 'Notification armed.',
  reminderNotifyDenied: 'Notifications off. This screen is the reminder.',
  reminderPreview: 'Preview notification',
  reminderWent: 'I went',
  reminderNotToday: 'Not today',
  officerLink: 'List a room',
  campusLink: 'Campus',
  officerTitle: 'List a room',
  officerLead: 'First 15 minutes is required. No host names.',
  officerName: 'Name',
  officerFirst15: 'First 15 minutes',
  officerStay: 'Stay / leave',
  officerHours: 'Hours',
  officerNext: 'Next meeting',
  officerNotFit: 'Not a fit if',
  officerWalk: 'Walk instruction',
  officerNights: 'Nights',
  officerDropIn: 'Drop-in',
  officerSubmit: 'List this room',
  officerListed: 'Listed. It can show on this week’s plan.',
  campusTitle: 'Campus',
  campusLead: '~50 interviews before names appear on a club.',
  campusClosed: 'People closed.',
  campusOpen: 'People open — names only on the club they attend.',
  campusOpenCta: 'Simulate 50 interviews',
  campusCloseCta: 'Close people',
  homePeopleOpen: 'Names only on the club they attend.',
  afterLead: 'Two taps.',
  stayQ: 'Stay past 15?',
  returnQ: 'Go back next week?',
  sceneQ: "What was true in the room?",
  sceneHelper: 'A detail that was not in the profile.',
  afterSave: 'Save',
  reportTitle: 'Report',
  reportLead: 'This stays off the public card.',
  reportPlaceholder: 'What happened?',
  reportSubmit: 'Submit report',
  reportDone: 'Report saved on this device.',
  blockTitle: 'Block',
  blockLead: 'This club will leave your weekly plan. You can start another first pass later.',
  blockLeadPerson: 'This person will not show as also at a meeting. Clubs stay. No messages either way.',
  blockConfirm: 'Block this club',
  blockConfirmPerson: 'Block this person',
  blockDone: 'Blocked. It will not show on home.',
  blockDonePerson: 'Blocked. They will not show on a club card.',
  cardTitle: 'Your card',
  cardPrivacy: 'The interview stays private.',
  cardHint: '1–2 sentences. We will not rewrite them.',
  cardSave: 'Save',
  safetyLink: 'Report',
  blockLink: 'Block',
  editCard: 'Edit public card',
  reminderLink: 'Day-of reminder',
  afterLink: 'After a visit',
  yes: 'Yes',
  no: 'No',
} as const;
