export const PLAN_COPY = {
  firstPass: 'FIRST PASS',
  unlockLead: "Here's a first pass. 3 clubs this week. It gets less random as you get more specific.",
  unlockCta: "See this week's plan",
  homeKicker: 'This week',
  homeLead: 'A short plan. Show up to a room — not a chat.',
  homePeopleClosed: 'People are not on this pass. Clubs first.',
  first15: 'First 15 minutes',
  stayLeave: 'Stay / leave',
  thisWeek: 'This week',
  nextMeeting: 'Next meeting',
  notFit: 'Not a fit if',
  ifThen: 'If-then',
  dropIn: 'Low commitment — drop in is fine.',
  illGo: "I'll go",
  illGoDone: "You're going. We'll remind you with this same line.",
  alsoAt: 'Also at this meeting',
  reminderTitle: 'Today',
  reminderEmpty: "You haven't said I'll go yet. The reminder is the same if-then you commit — we won't invent a new one.",
  reminderNote: "This is the same if-then you committed. We won't invent a new one.",
  reminderWent: 'I went',
  reminderNotToday: 'Not today',
  afterLead: 'Two taps. Show-up is the point. Coming back within 14 days is the companion.',
  stayQ: 'Did you stay past 15 minutes?',
  returnQ: 'Would you go back next week?',
  sceneQ: "What was true in the room that wasn't in the profile?",
  sceneHelper: 'A real detail from the room. Not whether you made a friend.',
  afterSave: 'Save this visit',
  reportTitle: 'Report',
  reportLead: 'Tell us what was wrong. This stays off the public card.',
  reportPlaceholder: 'What happened?',
  reportSubmit: 'Submit report',
  reportDone: 'Report saved on this device.',
  blockTitle: 'Block',
  blockLead: 'This club will leave your weekly plan. You can start another first pass later.',
  blockConfirm: 'Block this club',
  blockDone: 'Blocked. It will not show on home.',
  cardTitle: 'Your public card',
  cardPrivacy: 'The interview stays private. Other students only see this short card.',
  cardHint: '1–2 sentences in your words. We will not rewrite them.',
  cardSave: 'Save card',
  safetyLink: 'Report',
  blockLink: 'Block',
  editCard: 'Edit public card',
  reminderLink: 'Day-of reminder',
  afterLink: 'After a visit',
  yes: 'Yes',
  no: 'No',
} as const;
